app:
  name: "dikdok"
  mode: "dev"
  port: "8081"
log:
  level: "debug"
  filename: "dikdok.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "dikdok_db"